# Generated by Django 4.2.20 on 2025-05-15 13:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("records", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="record",
            name="is_staff_pick",
            field=models.BooleanField(
                default=False,
                help_text="Tick to feature this record on the homepage as a staff pick",
            ),
        ),
    ]
